[package]
name = "pre-commit-mail-selection"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
dialoguer = "0.11.0"
git2 = "0.20.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.20"
